"""chore(migration): auto-generated on 7d205ffdd04bf9aaab3f7e6b566f258ec964e1a0

Revision ID: 06a2feb05f46
Revises: 0a77ff84dca2
Create Date: 2025-07-26 21:13:48.256061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06a2feb05f46'
down_revision: Union[str, None] = '0a77ff84dca2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
