"""chore(migration): auto-generated on b29d47c646e082a8315a1a20c4dbd39d0ebf6d9b

Revision ID: 08b0115b7974
Revises: 0bf8eeaa4844
Create Date: 2025-08-20 10:25:30.796163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08b0115b7974'
down_revision: Union[str, None] = '0bf8eeaa4844'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
