"""chore(migration): auto-generated on b54a1917f5299cbfedcc398999355e4e9d15f183
Revision ID: 0bf8eeaa4844
Revises: d3634510f1c5
Create Date: 2025-08-18 15:38:55.250046
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bf8eeaa4844'
down_revision: Union[str, None] = 'd3634510f1c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'event_table',
        sa.Column(
            'event_users_confirmed',
            sa.Boolean(),
            nullable=False,
            server_default=sa.false()  # set default for existing rows
        )
    )
    # drop the default so future inserts must set it explicitly
    op.alter_column(
        'event_table',
        'event_users_confirmed',
        server_default=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_table', 'event_users_confirmed')
    # ### end Alembic commands ###
