"""chore(migration): auto-generated on 1c61692ef03c574dfde719d34f2e433e6f959c4a

Revision ID: 0ced491861d6
Revises: 05bcabd34057
Create Date: 2025-07-25 10:49:50.543628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ced491861d6'
down_revision: Union[str, None] = '05bcabd34057'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
