"""chore(migration): auto-generated on f5fdc1dddf48340ba36791e715bc7266f4c7c4ee

Revision ID: 0e269b8bc5d9
Revises: 355587cbf246
Create Date: 2026-02-26 15:44:03.788169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e269b8bc5d9'
down_revision: Union[str, None] = '355587cbf246'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
