"""chore(migration): auto-generated on 71bc85061dab09c301c286be9c5eda1f75fe1d5b

Revision ID: 10c7e649634f
Revises: 45e7832be45e
Create Date: 2026-08-14 15:11:36.373210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10c7e649634f'
down_revision: Union[str, None] = '45e7832be45e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('adventure_mission_table', sa.Column('unlock_code', sa.String(length=200), nullable=True))
    op.add_column('adventure_mission_table', sa.Column('unlock_hint_sv', sa.String(length=200), nullable=True))
    op.add_column('adventure_mission_table', sa.Column('unlock_hint_en', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('adventure_mission_table', 'unlock_hint_en')
    op.drop_column('adventure_mission_table', 'unlock_hint_sv')
    op.drop_column('adventure_mission_table', 'unlock_code')
    # ### end Alembic commands ###
