"""chore(migration): auto-generated on e875a93cbff0f8829f0636f464d3444743154182

Revision ID: 19391146e947
Revises: 355587cbf246
Create Date: 2026-02-23 17:06:07.833335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19391146e947'
down_revision: Union[str, None] = '355587cbf246'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
