"""chore(migration): auto-generated on 11757da11f61a6460edd81a996cf8eff3b46b40a

Revision ID: 206631fafbce
Revises: 3e3f462da872
Create Date: 2025-07-24 20:59:41.602568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '206631fafbce'
down_revision: Union[str, None] = '3e3f462da872'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
