"""chore(migration): auto-generated on 27edfe9eedcc42b2f8bb70bbefa1803c6df00967

Revision ID: 2108c7a47a9a
Revises: 30ef9e4834db
Create Date: 2025-09-29 15:39:51.829665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2108c7a47a9a'
down_revision: Union[str, None] = '30ef9e4834db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
