"""chore(migration): auto-generated on 59231dcd18e88acf278ecd7430d05176354856a5

Revision ID: 21aa14a751e0
Revises: 279e097dc5f4
Create Date: 2025-07-27 17:56:37.371670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21aa14a751e0'
down_revision: Union[str, None] = '279e097dc5f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
