"""chore(migration): auto-generated on 142968217d3fe1bfaf9b5941ca3fe16f20afc14d

Revision ID: 2429c778c99d
Revises: 58ef994bb4f9
Create Date: 2025-07-29 12:19:08.415236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2429c778c99d'
down_revision: Union[str, None] = '58ef994bb4f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
