"""chore(migration): auto-generated on e467b5afeaea2dfc0385f7cd1f7d7f7fe6e3471f

Revision ID: 26b5e2ba74f6
Revises: 355587cbf246
Create Date: 2026-02-23 17:07:01.174234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26b5e2ba74f6'
down_revision: Union[str, None] = '355587cbf246'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
