"""chore(migration): auto-generated on 660dba1e3f39e9433271132ed95193ae0baf0e32

Revision ID: 273aa5fac8c3
Revises: 0bf8eeaa4844
Create Date: 2025-08-25 17:26:07.938626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '273aa5fac8c3'
down_revision: Union[str, None] = '0bf8eeaa4844'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
