"""chore(migration): auto-generated on 30908825e96e59c82373372dbdea343a61306dd6

Revision ID: 279e097dc5f4
Revises: 0a77ff84dca2
Create Date: 2025-07-27 16:53:57.885047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '279e097dc5f4'
down_revision: Union[str, None] = '0a77ff84dca2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute(
        """
        UPDATE permission_table
        SET target = 'AdventureMissions'
        WHERE target = 'Adventure Missions';
        """
    )
    op.execute(
        """
        UPDATE permission_table
        SET target = 'RoomBookings'
        WHERE target = 'Room Bookings';
        """
    )
    
    op.alter_column('permission_table', 'target',
               existing_type=sa.VARCHAR(length=18),
               type_=sa.Enum('Event', 'Document', 'User', 'Post', 'Permission', 'News', 'Song', 'Ads', 'Gallery', 'Car', 'Cafe', 'Election', 'Groups', 'AdventureMissions', 'Nollning', 'UserDoorAccess', 'Tags', 'Council', 'RoomBookings', 'Moosegame', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute(
        """
        UPDATE permission_table
        SET target = 'Adventure Missions'
        WHERE target = 'AdventureMissions';
        """
    )
    op.execute(
        """
        UPDATE permission_table
        SET target = 'Room Bookings'
        WHERE target = 'RoomBookings';
        """
    )
    
    op.alter_column('permission_table', 'target',
               existing_type=sa.Enum('Event', 'Document', 'User', 'Post', 'Permission', 'News', 'Song', 'Ads', 'Gallery', 'Car', 'Cafe', 'Election', 'Groups', 'AdventureMissions', 'Nollning', 'UserDoorAccess', 'Tags', 'Council', 'RoomBookings', 'Moosegame', native_enum=False),
               type_=sa.VARCHAR(length=18),
               existing_nullable=False)
    # ### end Alembic commands ###
