"""chore(migration): auto-generated on 01392511518529415477e7b83833fd6491bbf6fc

Revision ID: 28208fb0745b
Revises: bab4b99afc6c
Create Date: 2025-07-30 14:29:37.833283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28208fb0745b'
down_revision: Union[str, None] = 'bab4b99afc6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
