"""chore(migration): auto-generated on 3c42d96a91fb4111bde7b9f58cf55b03c10ab3ef

Revision ID: 2b8797bbbd43
Revises: 30ef9e4834db
Create Date: 2025-10-22 20:28:02.843431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b8797bbbd43'
down_revision: Union[str, None] = '30ef9e4834db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
