"""chore(migration): auto-generated on 84e9ae46caf372721886af81a12e54adb4e76208

Revision ID: 2fc43f0f3e0a
Revises: 0bf8eeaa4844
Create Date: 2025-08-18 18:39:06.507445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fc43f0f3e0a'
down_revision: Union[str, None] = '0bf8eeaa4844'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
