"""chore(migration): auto-generated on d715ffe00db8d81a1f15d495e89cc140ec22afb2

Revision ID: 30ef9e4834db
Revises: 08ca8f1cd7d0
Create Date: 2025-09-17 16:47:11.720298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30ef9e4834db'
down_revision: Union[str, None] = '08ca8f1cd7d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('room_booking_table', 'room',
               existing_type=sa.VARCHAR(length=6),
               type_=sa.Enum('LC', 'Alumni', 'SK', 'Hilbert Cafe', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('room_booking_table', 'room',
               existing_type=sa.Enum('LC', 'Alumni', 'SK', 'Hilbert Cafe', native_enum=False),
               type_=sa.VARCHAR(length=6),
               existing_nullable=False)
    # ### end Alembic commands ###
