"""chore(migration): auto-generated on ecd14edba7a74d57cfa37a97e9d20721620dec8b

Revision ID: 355587cbf246
Revises: 30ef9e4834db
Create Date: 2025-10-22 20:30:49.236082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '355587cbf246'
down_revision: Union[str, None] = '30ef9e4834db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guild_meeting_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title_sv', sa.String(length=200), nullable=False),
    sa.Column('title_en', sa.String(length=200), nullable=False),
    sa.Column('date_description_sv', sa.String(length=500), nullable=False),
    sa.Column('date_description_en', sa.String(length=500), nullable=False),
    sa.Column('description_sv', sa.String(length=10000), nullable=False),
    sa.Column('description_en', sa.String(length=10000), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.CheckConstraint('id = 1', name='ck_guild_meeting_singleton'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('guild_meeting_table')
    # ### end Alembic commands ###
