"""chore(migration): auto-generated on 1fed5b740c07b1d93fa28e01b414742c37e8b927

Revision ID: 36872451d7ab
Revises: 58ef994bb4f9
Create Date: 2025-07-29 14:11:14.657982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36872451d7ab'
down_revision: Union[str, None] = '58ef994bb4f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
