"""chore(migration): auto-generated on de5e87a067a72816acee3841599c0b96bfbe30c1

Revision ID: 3692442d719e
Revises: 279e097dc5f4
Create Date: 2025-07-28 13:35:25.864940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3692442d719e'
down_revision: Union[str, None] = '279e097dc5f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
