"""chore(migration): auto-generated on 81c91026ae6219b0813b0a058ad302b4445024ec

Revision ID: 380b81b52b11
Revises: 3e3f462da872
Create Date: 2025-07-24 14:46:55.592066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '380b81b52b11'
down_revision: Union[str, None] = '3e3f462da872'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
