"""chore(migration): auto-generated on 5ee19cf74d565e7a866fb59c4e6fb291d46b2c92

Revision ID: 3a95dfcfc297
Revises: d3634510f1c5
Create Date: 2025-08-18 15:26:35.910938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a95dfcfc297'
down_revision: Union[str, None] = 'd3634510f1c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
