"""chore(migration): auto-generated on c6a8229724a1764826023703b1a403c854eaf278

Revision ID: 3e3f462da872
Revises: 57f351871f19
Create Date: 2025-07-24 13:00:07.475131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e3f462da872'
down_revision: Union[str, None] = '57f351871f19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
