"""chore(migration): auto-generated on c051d87ea6431da0375b0a403f27c29ea8c02407

Revision ID: 3eba901c0550
Revises: 0a77ff84dca2
Create Date: 2025-07-26 16:13:05.963954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3eba901c0550'
down_revision: Union[str, None] = '0a77ff84dca2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
