"""chore(migration): auto-generated on da6d613cdac02ef26478e40c7675ac4e2008169b

Revision ID: 3f01b50f10f6
Revises: 0a77ff84dca2
Create Date: 2025-07-27 11:56:42.943491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f01b50f10f6'
down_revision: Union[str, None] = '0a77ff84dca2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
