"""Initial migration

Revision ID: 4171070b8209
Revises: 
Create Date: 2025-01-30 18:56:03.624335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4171070b8209'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('album_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('council_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('election_table',
    sa.Column('election_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('start_time', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('end_time', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.PrimaryKeyConstraint('election_id')
    )
    op.create_table('group_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('group_type', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nollning_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permission_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=160), nullable=False),
    sa.Column('target', sa.String(length=160), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('songcategory_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tag_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=25), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('telephone_number', sa.String(length=20), nullable=False),
    sa.Column('start_year', sa.Integer(), nullable=False),
    sa.Column('account_created', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('program', sa.Enum('F', 'N', 'Pi', name='program_enum'), nullable=True),
    sa.Column('member_type', sa.String(length=200), nullable=True),
    sa.Column('is_member', sa.Boolean(), nullable=False),
    sa.Column('want_notifications', sa.Boolean(), nullable=False),
    sa.Column('stil_id', sa.String(), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_table_email'), 'user_table', ['email'], unique=True)
    op.create_table('adventure_mission_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nollning_id', sa.Integer(), nullable=False),
    sa.Column('nollning_week', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('max_points', sa.Integer(), nullable=False),
    sa.Column('min_points', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['nollning_id'], ['nollning_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bookad_table',
    sa.Column('ad_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('course', sa.String(length=100), nullable=True),
    sa.Column('author', sa.String(length=100), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('selling', sa.Boolean(), nullable=False),
    sa.Column('condition', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.id'], ),
    sa.PrimaryKeyConstraint('ad_id')
    )
    op.create_table('cafe_shift_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('starts_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('ends_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candidate_table',
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('election_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['election_id'], ['election_table.election_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.id'], ),
    sa.PrimaryKeyConstraint('candidate_id')
    )
    op.create_table('car_booking_table',
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('end_time', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.id'], ),
    sa.PrimaryKeyConstraint('booking_id')
    )
    op.create_table('event_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('starts_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('ends_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('signup_start', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('signup_end', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('title_sv', sa.String(length=100), nullable=False),
    sa.Column('title_en', sa.String(length=100), nullable=False),
    sa.Column('description_sv', sa.String(length=3000), nullable=False),
    sa.Column('description_en', sa.String(length=3000), nullable=False),
    sa.Column('council_id', sa.Integer(), nullable=False),
    sa.Column('max_event_users', sa.Integer(), nullable=False),
    sa.Column('all_day', sa.Boolean(), nullable=False),
    sa.Column('signup_not_opened_yet', sa.Boolean(), nullable=False),
    sa.Column('recurring', sa.Boolean(), nullable=False),
    sa.Column('drink', sa.Boolean(), nullable=False),
    sa.Column('food', sa.Boolean(), nullable=False),
    sa.Column('cash', sa.Boolean(), nullable=False),
    sa.Column('closed', sa.Boolean(), nullable=False),
    sa.Column('can_signup', sa.Boolean(), nullable=False),
    sa.Column('drink_package', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['council_id'], ['council_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_user_table',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('group_user_type', sa.Enum('Mentor', 'Mentee', 'Default', native_enum=False), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group_table.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'group_id')
    )
    op.create_table('img_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('album_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['album_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('news_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title_sv', sa.String(length=100), nullable=False),
    sa.Column('title_en', sa.String(length=100), nullable=False),
    sa.Column('content_sv', sa.String(length=3000), nullable=False),
    sa.Column('content_en', sa.String(length=3000), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('bumped_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('pinned_from', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('pinned_to', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nollning_group_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nollning_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group_table.id'], ),
    sa.ForeignKeyConstraint(['nollning_id'], ['nollning_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=90), nullable=False),
    sa.Column('council_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['council_id'], ['council_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('song_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.String(length=3000), nullable=False),
    sa.Column('author', sa.String(length=200), nullable=True),
    sa.Column('melody', sa.String(length=200), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['songcategory_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('election_post_table',
    sa.Column('election_post_id', sa.Integer(), nullable=False),
    sa.Column('election_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['election_id'], ['election_table.election_id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['post_table.id'], ),
    sa.PrimaryKeyConstraint('election_post_id')
    )
    op.create_table('event_tag_table',
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event_table.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag_table.id'], ),
    sa.PrimaryKeyConstraint('tag_id', 'event_id')
    )
    op.create_table('event_user_table',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(), nullable=True),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('latest_modified', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event_table.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'event_id')
    )
    op.create_table('group_mission_table',
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('adventure_mission_id', sa.Integer(), nullable=False),
    sa.Column('nollning_group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['adventure_mission_id'], ['adventure_mission_table.id'], ),
    sa.ForeignKeyConstraint(['nollning_group_id'], ['nollning_group_table.id'], ),
    sa.PrimaryKeyConstraint('adventure_mission_id', 'nollning_group_id')
    )
    op.create_table('news_tag_table',
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('news_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['news_id'], ['news_table.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag_table.id'], ),
    sa.PrimaryKeyConstraint('tag_id', 'news_id')
    )
    op.create_table('post_permission_table',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permission_table.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['post_table.id'], ),
    sa.PrimaryKeyConstraint('post_id', 'permission_id')
    )
    op.create_table('post_user_table',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post_table.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'post_id')
    )
    op.create_table('priority_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candidations_table',
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('election_post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_table.candidate_id'], ),
    sa.ForeignKeyConstraint(['election_post_id'], ['election_post_table.election_post_id'], ),
    sa.PrimaryKeyConstraint('candidate_id', 'election_post_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('candidations_table')
    op.drop_table('priority_table')
    op.drop_table('post_user_table')
    op.drop_table('post_permission_table')
    op.drop_table('news_tag_table')
    op.drop_table('group_mission_table')
    op.drop_table('event_user_table')
    op.drop_table('event_tag_table')
    op.drop_table('election_post_table')
    op.drop_table('song_table')
    op.drop_table('post_table')
    op.drop_table('nollning_group_table')
    op.drop_table('news_table')
    op.drop_table('img_table')
    op.drop_table('group_user_table')
    op.drop_table('event_table')
    op.drop_table('car_booking_table')
    op.drop_table('candidate_table')
    op.drop_table('cafe_shift_table')
    op.drop_table('bookad_table')
    op.drop_table('adventure_mission_table')
    op.drop_index(op.f('ix_user_table_email'), table_name='user_table')
    op.drop_table('user_table')
    op.drop_table('tag_table')
    op.drop_table('songcategory_table')
    op.drop_table('permission_table')
    op.drop_table('nollning_table')
    op.drop_table('group_table')
    op.drop_table('election_table')
    op.drop_table('council_table')
    op.drop_table('album_table')
    # ### end Alembic commands ###
