"""chore(migration): auto-generated on 7c5a58a1c3db48ac226fa32a9af8b7284a0fd2fe

Revision ID: 45e7832be45e
Revises: 8479c3bc82f8
Create Date: 2026-08-11 16:04:19.007650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45e7832be45e'
down_revision: Union[str, None] = '8479c3bc82f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prereg_member_table',
    sa.Column('prereg_member_id', sa.Integer(), nullable=False),
    sa.Column('telephone_number', sa.String(length=25), nullable=True),
    sa.Column('stil_id', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.CheckConstraint('telephone_number IS NOT NULL OR stil_id IS NOT NULL OR email IS NOT NULL', name='at_least_one_identifier_required'),
    sa.PrimaryKeyConstraint('prereg_member_id'),
    sa.UniqueConstraint('telephone_number', 'stil_id', 'email', name='unique_all', postgresql_nulls_not_distinct=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prereg_member_table')
    # ### end Alembic commands ###
