"""chore(migration): auto-generated on 987700d1f7b6b2caf26dd4ab1d1e6db58da8b4fe

Revision ID: 4647b1a2f1b9
Revises: 45e7832be45e
Create Date: 2026-08-13 18:55:46.357976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4647b1a2f1b9'
down_revision: Union[str, None] = '45e7832be45e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('adventure_mission_table', sa.Column('unlock_code', sa.String(length=200), nullable=True))
    op.add_column('adventure_mission_table', sa.Column('unlock_hint_sv', sa.String(length=200), nullable=True))
    op.add_column('adventure_mission_table', sa.Column('unlock_hint_en', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('adventure_mission_table', 'unlock_hint_en')
    op.drop_column('adventure_mission_table', 'unlock_hint_sv')
    op.drop_column('adventure_mission_table', 'unlock_code')
    # ### end Alembic commands ###
