"""chore(migration): auto-generated on c0c0009f7a23ba800d2c9c277d75aece072784d6

Revision ID: 472e83751eae
Revises: bab4b99afc6c
Create Date: 2025-07-31 14:58:53.517328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '472e83751eae'
down_revision: Union[str, None] = 'bab4b99afc6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photographer_table',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('album_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['album_table.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'album_id')
    )
    op.drop_constraint('album_table_photographer_id_fkey', 'album_table', type_='foreignkey')
    op.drop_column('album_table', 'photographer_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('album_table', sa.Column('photographer_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('album_table_photographer_id_fkey', 'album_table', 'user_table', ['photographer_id'], ['id'])
    op.drop_table('photographer_table')
    # ### end Alembic commands ###
