"""chore(migration): auto-generated on 87fec60f755af9c2a4b0fbce3c1addbe595fd20a

Revision ID: 4afac907f1c9
Revises: 08ca8f1cd7d0
Create Date: 2025-09-15 23:54:48.382093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4afac907f1c9'
down_revision: Union[str, None] = '08ca8f1cd7d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
