"""chore(migration): auto-generated on dd331ea0b19cf18a6c728e28d8feccc1ccf17b31

Revision ID: 4b3fc6811e70
Revises: 58ef994bb4f9
Create Date: 2025-07-29 21:25:16.639139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b3fc6811e70'
down_revision: Union[str, None] = '58ef994bb4f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
