"""chore(migration): auto-generated on b5556e6c9a4515e94058d298bbf10a034f52ca71

Revision ID: 4c52e45c5ed3
Revises: 608a17ac0dfc
Create Date: 2025-08-04 12:22:52.487449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c52e45c5ed3'
down_revision: Union[str, None] = '608a17ac0dfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('photographer_table', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('photographer_table', 'album_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('photographer_table', 'album_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('photographer_table', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
