"""chore(migration): auto-generated on 7e8a62a88fdca65470fb7fafbc75be2af0481c98

Revision ID: 4c547593618f
Revises: 355587cbf246
Create Date: 2026-03-28 14:11:01.961190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c547593618f'
down_revision: Union[str, None] = '355587cbf246'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
