"""chore(migration): auto-generated on 052b6847f762297d64083c7f0687e3303b706713

Revision ID: 4e2ea2ce6b59
Revises: 0bf8eeaa4844
Create Date: 2025-08-18 21:09:58.052345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e2ea2ce6b59'
down_revision: Union[str, None] = '0bf8eeaa4844'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
