"""chore(migration): auto-generated on 2aa67ebcfd6d7eeedfb0e09035cfb766f84b42ca

Revision ID: 4f59f08409ec
Revises: 0bf8eeaa4844
Create Date: 2025-08-18 17:32:25.730751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f59f08409ec'
down_revision: Union[str, None] = '0bf8eeaa4844'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
