"""chore(migration): auto-generated on dd76a49ebeb9adafea488bcc1df6e4cb15d2c725

Revision ID: 51a3c6c6b4a2
Revises: 355587cbf246
Create Date: 2026-03-23 17:34:04.491813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51a3c6c6b4a2'
down_revision: Union[str, None] = '355587cbf246'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
