"""chore(migration): auto-generated on d150020b388a25c32a2ad6c8a1352b03ea9ad3ae

Revision ID: 537cdb51032a
Revises: d3634510f1c5
Create Date: 2025-08-16 10:22:29.508609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '537cdb51032a'
down_revision: Union[str, None] = 'd3634510f1c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
