"""chore(migration): auto-generated on 82fe7a7cca2e6bd7dd5ae1bccc1c51e99e4b0ca1

Revision ID: 55274f928852
Revises: 0bf8eeaa4844
Create Date: 2025-08-18 18:57:59.284766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55274f928852'
down_revision: Union[str, None] = '0bf8eeaa4844'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
