"""chore(migration): auto-generated on 440f010badb90815eaebd88039593498b7818c6a

Revision ID: 57f351871f19
Revises: 883fd3ab9d8b
Create Date: 2025-07-24 12:29:44.208054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57f351871f19'
down_revision: Union[str, None] = '883fd3ab9d8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
