"""chore(migration): auto-generated on 21c5af50d02b196af8c5af677288f39a56364c0b

Revision ID: 58ef994bb4f9
Revises: c85cf8627725
Create Date: 2025-07-28 15:34:33.165960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58ef994bb4f9'
down_revision: Union[str, None] = 'c85cf8627725'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_door_access_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('door', sa.Enum('LC', 'Bunkern', 'Syster Kents', 'Cafét', 'Caféförrådet', 'Pubförrådet', 'Containern', 'Arkivet', native_enum=False), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_door_access_table')
    # ### end Alembic commands ###
