"""chore(migration): auto-generated on 7625e5472b356f5a9dec3d9f328d8dc2d7f5c59e

Revision ID: 5fc6791c2b4c
Revises: 8eb5c2e74727
Create Date: 2025-09-05 11:12:49.647244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fc6791c2b4c'
down_revision: Union[str, None] = '8eb5c2e74727'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
