"""chore(migration): auto-generated on 5dafb688f97f396b941c6a033464bc10f8d91b2b

Revision ID: 608a17ac0dfc
Revises: bab4b99afc6c
Create Date: 2025-07-31 18:13:08.416325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '608a17ac0dfc'
down_revision: Union[str, None] = 'bab4b99afc6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photographer_table',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('album_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['album_table.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'album_id')
    )
    op.add_column('adventure_mission_table', sa.Column('title_sv', sa.String(length=200), nullable=False))
    op.add_column('adventure_mission_table', sa.Column('title_en', sa.String(length=200), nullable=False))
    op.add_column('adventure_mission_table', sa.Column('description_sv', sa.String(length=2000), nullable=False))
    op.add_column('adventure_mission_table', sa.Column('description_en', sa.String(length=2000), nullable=False))
    op.drop_column('adventure_mission_table', 'title')
    op.drop_column('adventure_mission_table', 'description')
    op.drop_constraint('album_table_photographer_id_fkey', 'album_table', type_='foreignkey')
    op.drop_column('album_table', 'photographer_id')
    op.add_column('nollning_table', sa.Column('year', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'nollning_table', ['year'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'nollning_table', type_='unique')
    op.drop_column('nollning_table', 'year')
    op.add_column('album_table', sa.Column('photographer_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('album_table_photographer_id_fkey', 'album_table', 'user_table', ['photographer_id'], ['id'])
    op.add_column('adventure_mission_table', sa.Column('description', sa.VARCHAR(length=2000), autoincrement=False, nullable=False))
    op.add_column('adventure_mission_table', sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.drop_column('adventure_mission_table', 'description_en')
    op.drop_column('adventure_mission_table', 'description_sv')
    op.drop_column('adventure_mission_table', 'title_en')
    op.drop_column('adventure_mission_table', 'title_sv')
    op.drop_table('photographer_table')
    # ### end Alembic commands ###
