"""chore(migration): auto-generated on 0f4f6c0ed1ff3e4b90f9f4901b57874d8250ed20

Revision ID: 675fc06879a4
Revises: 8c1802607f1b
Create Date: 2025-07-24 22:18:55.802381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '675fc06879a4'
down_revision: Union[str, None] = '8c1802607f1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event_user_table', 'confirmed_status',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event_user_table', 'confirmed_status',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
