"""chore(migration): auto-generated on f0b7fb158ef3dcd4a2d34be4d6905f8497a0c38e

Revision ID: 67cadb6e0b4e
Revises: d3634510f1c5
Create Date: 2025-08-15 13:23:27.876511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67cadb6e0b4e'
down_revision: Union[str, None] = 'd3634510f1c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
