"""chore(migration): auto-generated on 3a732b3c482f5f1d7a60acc4c4d75a80c8afa57b

Revision ID: 6c2bad20dae0
Revises: f8de51ea2a13
Create Date: 2025-08-06 15:26:08.995785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c2bad20dae0'
down_revision: Union[str, None] = 'f8de51ea2a13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
