"""chore(migration): auto-generated on 6e63e489220fe3080c5f44cc1d697c64eb5eaf72

Revision ID: 6c7cfbfd4497
Revises: 05bcabd34057
Create Date: 2025-07-25 14:01:28.635343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c7cfbfd4497'
down_revision: Union[str, None] = '05bcabd34057'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
