"""chore(migration): auto-generated on d713064409498d4002f48ff31d90a1546a600be7

Revision ID: 6e40f45b5845
Revises: d3634510f1c5
Create Date: 2025-08-18 14:20:56.085378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e40f45b5845'
down_revision: Union[str, None] = 'd3634510f1c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
