"""chore(migration): auto-generated on 00244edda56f7dba109cd110c77e9e33220b7c41

Revision ID: 702a5fe1f3d9
Revises: 0bf8eeaa4844
Create Date: 2025-08-18 18:33:35.981770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '702a5fe1f3d9'
down_revision: Union[str, None] = '0bf8eeaa4844'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
