"""chore(migration): auto-generated on ad4c57bdf6faa24127e51e7abdc3d5feec011dae

Revision ID: 72d8e0a1d21f
Revises: 05bcabd34057
Create Date: 2025-07-25 10:59:26.680211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72d8e0a1d21f'
down_revision: Union[str, None] = '05bcabd34057'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
