"""chore(migration): auto-generated on fb74e547b5bf8e956cdb1065d5e9965089604c39

Revision ID: 74273a6f8046
Revises: 0bf8eeaa4844
Create Date: 2025-08-21 08:41:14.867098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74273a6f8046'
down_revision: Union[str, None] = '0bf8eeaa4844'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
