"""chore(migration): auto-generated on f3254c9f25d7ae4bd0b13c3da33a74dc040621bc

Revision ID: 77b7cd2c8260
Revises: 3e3f462da872
Create Date: 2025-07-24 21:05:51.972989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '77b7cd2c8260'
down_revision: Union[str, None] = '3e3f462da872'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('song_category_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('songcategory_table')
    op.add_column('bookad_table', sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False))
    op.alter_column('bookad_table', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('car_block_table', 'reason',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=False)
    op.drop_column('car_booking_table', 'user_last_name')
    op.drop_column('car_booking_table', 'user_first_name')
    op.alter_column('council_table', 'name_sv',
               existing_type=sa.VARCHAR(length=160),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('council_table', 'name_en',
               existing_type=sa.VARCHAR(length=160),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('event_table', 'dress_code',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('group_table', 'group_type',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Enum('Mentor', 'Mission', 'Default', 'Committee', native_enum=False),
               existing_nullable=False)
    op.alter_column('permission_table', 'action',
               existing_type=sa.VARCHAR(length=160),
               type_=sa.Enum('view', 'manage', 'super', native_enum=False),
               existing_nullable=False)
    op.alter_column('permission_table', 'target',
               existing_type=sa.VARCHAR(length=160),
               type_=sa.Enum('Event', 'Document', 'User', 'Post', 'Permission', 'News', 'Song', 'Ads', 'Gallery', 'Car', 'Cafe', 'Election', 'Groups', 'Adventure Missions', 'Nollning', 'UserDoorAccess', 'Tags', 'Council', 'Room Bookings', native_enum=False),
               existing_nullable=False)
    op.alter_column('post_table', 'name',
               existing_type=sa.VARCHAR(length=90),
               type_=sa.String(length=60),
               existing_nullable=False)
    op.alter_column('room_booking_table', 'description',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.drop_constraint('song_table_category_id_fkey', 'song_table', type_='foreignkey')
    op.create_foreign_key(None, 'song_table', 'song_category_table', ['category_id'], ['id'])
    op.add_column('user_door_access_table', sa.Column('endtime', sa.TIMESTAMP(timezone=True), nullable=False))
    op.drop_column('user_door_access_table', 'stoptime')
    op.drop_column('user_table', 'member_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_table', sa.Column('member_type', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('user_door_access_table', sa.Column('stoptime', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_column('user_door_access_table', 'endtime')
    op.drop_constraint(None, 'song_table', type_='foreignkey')
    op.create_foreign_key('song_table_category_id_fkey', 'song_table', 'songcategory_table', ['category_id'], ['id'])
    op.alter_column('room_booking_table', 'description',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('post_table', 'name',
               existing_type=sa.String(length=60),
               type_=sa.VARCHAR(length=90),
               existing_nullable=False)
    op.alter_column('permission_table', 'target',
               existing_type=sa.Enum('Event', 'Document', 'User', 'Post', 'Permission', 'News', 'Song', 'Ads', 'Gallery', 'Car', 'Cafe', 'Election', 'Groups', 'Adventure Missions', 'Nollning', 'UserDoorAccess', 'Tags', 'Council', 'Room Bookings', native_enum=False),
               type_=sa.VARCHAR(length=160),
               existing_nullable=False)
    op.alter_column('permission_table', 'action',
               existing_type=sa.Enum('view', 'manage', 'super', native_enum=False),
               type_=sa.VARCHAR(length=160),
               existing_nullable=False)
    op.alter_column('group_table', 'group_type',
               existing_type=sa.Enum('Mentor', 'Mission', 'Default', 'Committee', native_enum=False),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('event_table', 'dress_code',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('council_table', 'name_en',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=160),
               existing_nullable=False)
    op.alter_column('council_table', 'name_sv',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=160),
               existing_nullable=False)
    op.add_column('car_booking_table', sa.Column('user_first_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('car_booking_table', sa.Column('user_last_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.alter_column('car_block_table', 'reason',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('bookad_table', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('bookad_table', 'created_at')
    op.create_table('songcategory_table',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='songcategory_table_pkey')
    )
    op.drop_table('song_category_table')
    # ### end Alembic commands ###
