"""chore(migration): auto-generated on 13cdc32d1b5bf3a61e9434e5b0a79ac84c0a70cb

Revision ID: 7c423daff4d2
Revises: d3634510f1c5
Create Date: 2025-08-16 09:43:27.963582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c423daff4d2'
down_revision: Union[str, None] = 'd3634510f1c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
