"""chore(migration): auto-generated on 203044f29b4207fc52b15a8840e39d988a4c6a14

Revision ID: 815bd0c80e29
Revises: 355587cbf246
Create Date: 2026-03-30 17:42:53.016715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '815bd0c80e29'
down_revision: Union[str, None] = '355587cbf246'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
