"""chore(migration): auto-generated on 7f9d324ed161350a9b15a5d96b3447d3f58d3386

Revision ID: 815df61db709
Revises: 0a77ff84dca2
Create Date: 2025-07-27 12:14:52.408255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '815df61db709'
down_revision: Union[str, None] = '0a77ff84dca2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
