"""chore(migration): auto-generated on adca692eeb0e17f07430c7b6205f4626e59275fb

Revision ID: 822462d089b5
Revises: 08ca8f1cd7d0
Create Date: 2025-09-15 18:28:20.375258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '822462d089b5'
down_revision: Union[str, None] = '08ca8f1cd7d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
