"""chore(migration): auto-generated on ab2b4b62fcea6be2f02225d6fadc2f20b69f668c

Revision ID: 8479c3bc82f8
Revises: a6a861ab04ae
Create Date: 2026-08-01 12:59:22.711113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8479c3bc82f8'
down_revision: Union[str, None] = 'a6a861ab04ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_table', sa.Column('mentor_group_types', sa.JSON(), nullable=False, server_default=sa.text("""'["Mentor", "Mission", "Committee", "Default"]'""")))
    op.add_column('event_table', sa.Column('allow_other_mentors', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_table', 'allow_other_mentors')
    op.drop_column('event_table', 'mentor_group_types')
    # ### end Alembic commands ###
