"""chore(migration): auto-generated on 4eca62f5502da100bdef887ccdd8c5906e1d6147

Revision ID: 848162b72f4c
Revises: bab4b99afc6c
Create Date: 2025-07-31 13:09:01.036706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '848162b72f4c'
down_revision: Union[str, None] = 'bab4b99afc6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
