"""chore(migration): auto-generated on 75cf191153e7993950d6e90da915a9e46c05fc75

Revision ID: 85884da8065e
Revises: cb3be75c9ef1
Create Date: 2026-08-17 20:58:36.395676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85884da8065e'
down_revision: Union[str, None] = 'cb3be75c9ef1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('adventure_mission_table', sa.Column('mission_category', sa.Enum('Barbiedans', 'Fadder', 'Kreativ', 'Resa', 'Spel', 'Tävling', 'Älg', native_enum=False), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('adventure_mission_table', 'mission_category')
    # ### end Alembic commands ###
