"""chore(migration): auto-generated on f9e75bbcc53cb2d2d6161694077ff56df749c4fd

Revision ID: 86e421dc5d1a
Revises: f8de51ea2a13
Create Date: 2025-08-06 15:18:34.541418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86e421dc5d1a'
down_revision: Union[str, None] = 'f8de51ea2a13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
