"""chore(migration): auto-generated on d9c1f0f3e5e3060c7ffac857867070dbbac28352

Revision ID: 882047e8f52c
Revises: 30ef9e4834db
Create Date: 2025-10-22 20:25:58.046428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '882047e8f52c'
down_revision: Union[str, None] = '30ef9e4834db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
