"""chore(migration): auto-generated on 457473c4a1ab3de136a189819e886c8f68180a1a

Revision ID: 883fd3ab9d8b
Revises: d57390e0ff04
Create Date: 2025-07-24 12:02:54.305306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '883fd3ab9d8b'
down_revision: Union[str, None] = 'd57390e0ff04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('council_table', sa.Column('name_sv', sa.String(length=160), nullable=False))
    op.add_column('council_table', sa.Column('name_en', sa.String(length=160), nullable=False))
    op.add_column('council_table', sa.Column('description_sv', sa.String(length=2500), nullable=True))
    op.add_column('council_table', sa.Column('description_en', sa.String(length=2500), nullable=True))
    op.drop_constraint('council_table_name_key', 'council_table', type_='unique')
    op.create_unique_constraint(None, 'council_table', ['name_en'])
    op.create_unique_constraint(None, 'council_table', ['name_sv'])
    op.drop_column('council_table', 'name')
    op.drop_column('council_table', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('council_table', sa.Column('description', sa.VARCHAR(length=2500), autoincrement=False, nullable=True))
    op.add_column('council_table', sa.Column('name', sa.VARCHAR(length=160), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'council_table', type_='unique')
    op.drop_constraint(None, 'council_table', type_='unique')
    op.create_unique_constraint('council_table_name_key', 'council_table', ['name'])
    op.drop_column('council_table', 'description_en')
    op.drop_column('council_table', 'description_sv')
    op.drop_column('council_table', 'name_en')
    op.drop_column('council_table', 'name_sv')
    # ### end Alembic commands ###
