"""chore(migration): auto-generated on bfad858391e2a3cf3daa75d31e89b60bd6b8c452

Revision ID: 89df7aa2ad59
Revises: 8eb5c2e74727
Create Date: 2025-09-04 15:14:02.940741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89df7aa2ad59'
down_revision: Union[str, None] = '8eb5c2e74727'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
