"""chore(migration): auto-generated on 6e16ff3c54550aa90f337f85fd190fa62f2cd4ee

Revision ID: 8a7ffd69e9dc
Revises: 279e097dc5f4
Create Date: 2025-07-27 17:15:47.229963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a7ffd69e9dc'
down_revision: Union[str, None] = '279e097dc5f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
