"""chore(migration): auto-generated on ca02406991214ea8116832e0e7c8bbe9f0e724ce

Revision ID: 8c1802607f1b
Revises: 77b7cd2c8260
Create Date: 2025-07-24 22:03:17.479536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8c1802607f1b'
down_revision: Union[str, None] = '77b7cd2c8260'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 1) Drop the old enum-backed column entirely:
    op.drop_column('event_user_table', 'confirmed_status')

    # 2) Add it back as a boolean (all existing rows get NULL here—use server_default if you prefer False):
    op.add_column(
        'event_user_table',
        sa.Column('confirmed_status', sa.Boolean(), nullable=True)
    )

    # (Optional) If you want NOT NULL with default False, you could do:
    # op.add_column(
    #     'event_user_table',
    #     sa.Column('confirmed_status', sa.Boolean(), nullable=False, server_default=sa.false())
    # )
    # op.alter_column('event_user_table', 'confirmed_status', server_default=None)

    # Now your other autogenerated changes:
    op.add_column('post_table', sa.Column('name_sv', sa.String(length=60), nullable=False))
    op.add_column('post_table', sa.Column('name_en', sa.String(length=60), nullable=False))
    op.add_column('post_table', sa.Column('description_sv', sa.String(length=300), nullable=False))
    op.add_column('post_table', sa.Column('description_en', sa.String(length=300), nullable=False))
    op.add_column('post_table', sa.Column('email', sa.String(), nullable=False))
    op.drop_column('post_table', 'name')
    op.alter_column(
        'user_table', 'program',
        existing_type=sa.Enum('F', 'N', 'Pi', name='program_enum'),
        type_=sa.Enum('Oklart', 'F', 'Pi', 'N', native_enum=False),
        nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 1) Drop the boolean column...
    op.drop_column('event_user_table', 'confirmed_status')

    # 2) ...and restore the enum as it was before:
    op.add_column(
        'event_user_table',
        sa.Column(
            'confirmed_status',
            sa.Enum('confirmed', 'unconfirmed', name='confirmed_enum'),
            nullable=False
        )
    )

    # Revert the rest:
    op.alter_column(
        'user_table', 'program',
        existing_type=sa.Enum('Oklart', 'F', 'Pi', 'N', native_enum=False),
        type_=sa.Enum('F', 'N', 'Pi', name='program_enum'),
        nullable=True
    )
    op.add_column('post_table', sa.Column('name', sa.VARCHAR(length=60), nullable=False))
    op.drop_column('post_table', 'email')
    op.drop_column('post_table', 'description_en')
    op.drop_column('post_table', 'description_sv')
    op.drop_column('post_table', 'name_en')
    op.drop_column('post_table', 'name_sv')
    # ### end Alembic commands ###
