"""chore(migration): auto-generated on ca02406991214ea8116832e0e7c8bbe9f0e724ce

Revision ID: 8c1802607f1b
Revises: 77b7cd2c8260
Create Date: 2025-07-24 22:03:17.479536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8c1802607f1b'
down_revision: Union[str, None] = '77b7cd2c8260'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event_user_table', 'confirmed_status',
               existing_type=postgresql.ENUM('confirmed', 'unconfirmed', name='confirmed_enum'),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.add_column('post_table', sa.Column('name_sv', sa.String(length=60), nullable=False))
    op.add_column('post_table', sa.Column('name_en', sa.String(length=60), nullable=False))
    op.add_column('post_table', sa.Column('description_sv', sa.String(length=300), nullable=False))
    op.add_column('post_table', sa.Column('description_en', sa.String(length=300), nullable=False))
    op.add_column('post_table', sa.Column('email', sa.String(), nullable=False))
    op.drop_column('post_table', 'name')
    op.alter_column('user_table', 'program',
               existing_type=postgresql.ENUM('F', 'N', 'Pi', name='program_enum'),
               type_=sa.Enum('Oklart', 'F', 'Pi', 'N', native_enum=False),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_table', 'program',
               existing_type=sa.Enum('Oklart', 'F', 'Pi', 'N', native_enum=False),
               type_=postgresql.ENUM('F', 'N', 'Pi', name='program_enum'),
               nullable=True)
    op.add_column('post_table', sa.Column('name', sa.VARCHAR(length=60), autoincrement=False, nullable=False))
    op.drop_column('post_table', 'email')
    op.drop_column('post_table', 'description_en')
    op.drop_column('post_table', 'description_sv')
    op.drop_column('post_table', 'name_en')
    op.drop_column('post_table', 'name_sv')
    op.alter_column('event_user_table', 'confirmed_status',
               existing_type=sa.Boolean(),
               type_=postgresql.ENUM('confirmed', 'unconfirmed', name='confirmed_enum'),
               existing_nullable=False)
    # ### end Alembic commands ###
