"""chore(migration): auto-generated on 8bb8f4014c996dacc64f142019ae43c9e625fa5e

Revision ID: 8c1fc09fbd81
Revises: 30ef9e4834db
Create Date: 2025-10-02 14:31:14.835690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c1fc09fbd81'
down_revision: Union[str, None] = '30ef9e4834db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
