"""chore(migration): auto-generated on 7902f00e3823f3c36f1ea39e39760a1a836adead

Revision ID: 98f778f2227f
Revises: f8de51ea2a13
Create Date: 2025-08-14 14:15:15.133947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98f778f2227f'
down_revision: Union[str, None] = 'f8de51ea2a13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document_table', 'title',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=300),
               existing_nullable=False)
    op.alter_column('document_table', 'file_name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=300),
               existing_nullable=False)
    op.alter_column('document_table', 'category',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document_table', 'category',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.alter_column('document_table', 'file_name',
               existing_type=sa.String(length=300),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('document_table', 'title',
               existing_type=sa.String(length=300),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###
