"""chore(migration): auto-generated on 647311bc19fb22c6e1dad85d7029192f5cd18bc0

Revision ID: 9909e785b5aa
Revises: 0bf8eeaa4844
Create Date: 2025-08-20 10:27:44.932786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9909e785b5aa'
down_revision: Union[str, None] = '0bf8eeaa4844'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
