"""chore(migration): auto-generated on 0aa773f6b05f642bc41753b165edf06c07fd4655

Revision ID: a341ce2876af
Revises: 30ef9e4834db
Create Date: 2025-10-08 14:22:11.439987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a341ce2876af'
down_revision: Union[str, None] = '30ef9e4834db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
