"""chore(migration): auto-generated on ed51a78817f3ddd1a9ff9d1de1b9ea25ffffeeea

Revision ID: a36a93d0f222
Revises: de17c545e41d
Create Date: 2025-07-29 22:10:25.247334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a36a93d0f222'
down_revision: Union[str, None] = 'de17c545e41d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('group_mission_table', 'is_accepted',
               existing_type=postgresql.ENUM('Accepted', 'Failed', 'Review', name='mission_status'),
               type_=sa.Enum('Accepted', 'Failed', 'Review', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('group_mission_table', 'is_accepted',
               existing_type=sa.Enum('Accepted', 'Failed', 'Review', native_enum=False),
               type_=postgresql.ENUM('Accepted', 'Failed', 'Review', name='mission_status'),
               existing_nullable=False)
    # ### end Alembic commands ###
