"""chore(migration): auto-generated on 6581975d0f706a9d3b3f161fafe2cc9bdc728794

Revision ID: a6a861ab04ae
Revises: b708c464786f
Create Date: 2026-05-05 08:21:33.158487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6a861ab04ae'
down_revision: Union[str, None] = 'b708c464786f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_table', sa.Column('image_exist', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news_table', 'image_exist')
    # ### end Alembic commands ###
