"""chore(migration): auto-generated on d1b05b10dcf8822ed5f0523d0494b15156ded0fd

Revision ID: ae8dc95fb0cc
Revises: 608a17ac0dfc
Create Date: 2025-08-05 21:37:51.916527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae8dc95fb0cc'
down_revision: Union[str, None] = '608a17ac0dfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event_user_table', 'drinkPackage',
               existing_type=sa.VARCHAR(length=14),
               type_=sa.Enum('None', 'AlcoholFree', 'Alcohol', native_enum=False),
               existing_nullable=False)
    op.alter_column('photographer_table', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('photographer_table', 'album_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('photographer_table', 'album_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('photographer_table', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('event_user_table', 'drinkPackage',
               existing_type=sa.Enum('None', 'AlcoholFree', 'Alcohol', native_enum=False),
               type_=sa.VARCHAR(length=14),
               existing_nullable=False)
    # ### end Alembic commands ###
