"""chore(migration): auto-generated on 1346a91269fb3200ce00878098352924c2ed2d8f

Revision ID: b547084eda86
Revises: 355587cbf246
Create Date: 2025-12-23 22:47:12.606631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b547084eda86'
down_revision: Union[str, None] = '355587cbf246'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
