"""chore(migration): auto-generated on 612f95fb775ec916761b4b44ecdd61bc3f1c9150

Revision ID: b921ab38f0a1
Revises: 279e097dc5f4
Create Date: 2025-07-27 20:43:47.163185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b921ab38f0a1'
down_revision: Union[str, None] = '279e097dc5f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
