"""chore(migration): auto-generated on 6ddae6ed567adb11378893d04657063b47cdd515

Revision ID: ba1f503e111a
Revises: bab4b99afc6c
Create Date: 2025-07-30 13:44:23.848753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ba1f503e111a'
down_revision: Union[str, None] = 'bab4b99afc6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('group_mission_table', 'is_accepted',
               existing_type=postgresql.ENUM('Accepted', 'Failed', 'Review', name='mission_status'),
               type_=sa.Enum('Accepted', 'Failed', 'Review', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('group_mission_table', 'is_accepted',
               existing_type=sa.Enum('Accepted', 'Failed', 'Review', native_enum=False),
               type_=postgresql.ENUM('Accepted', 'Failed', 'Review', name='mission_status'),
               existing_nullable=False)
    # ### end Alembic commands ###
