"""added new fields

Revision ID: c6bbcfceb348
Revises: 4171070b8209
Create Date: 2025-05-19 16:06:13.084401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6bbcfceb348'
down_revision: Union[str, None] = '4171070b8209'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_door_access_table',
    sa.Column('user_access_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('door', sa.Enum('LC', 'Bunkern', 'Syster Kents', 'Cafét', 'Caféförrådet', 'Pubförrådet', 'Containern', 'Arkivet', native_enum=False), nullable=False),
    sa.Column('starttime', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('stoptime', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.id'], ),
    sa.PrimaryKeyConstraint('user_access_id')
    )
    op.add_column('album_table', sa.Column('year', sa.Integer(), nullable=False))
    op.add_column('album_table', sa.Column('location', sa.String(), nullable=False))
    op.add_column('album_table', sa.Column('date', sa.TIMESTAMP(timezone=True), nullable=False))
    op.add_column('album_table', sa.Column('title_sv', sa.String(length=40), nullable=False))
    op.add_column('album_table', sa.Column('title_en', sa.String(length=40), nullable=False))
    op.add_column('album_table', sa.Column('desc_sv', sa.String(length=123), nullable=False))
    op.add_column('album_table', sa.Column('desc_en', sa.String(length=123), nullable=False))
    op.add_column('album_table', sa.Column('photographer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'album_table', 'user_table', ['photographer_id'], ['id'])
    op.drop_column('album_table', 'name')
    op.add_column('council_table', sa.Column('description', sa.String(length=2500), nullable=True))
    op.add_column('event_table', sa.Column('location', sa.String(length=50), nullable=False))
    op.add_column('event_table', sa.Column('is_nollning_event', sa.Boolean(), nullable=False))
    op.add_column('event_user_table', sa.Column('drinkPackage', sa.String(), nullable=False))
    op.add_column('user_table', sa.Column('standard_food_preferences', sa.JSON(), nullable=False))
    op.add_column('user_table', sa.Column('other_food_preferences', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_table', 'other_food_preferences')
    op.drop_column('user_table', 'standard_food_preferences')
    op.drop_column('event_user_table', 'drinkPackage')
    op.drop_column('event_table', 'is_nollning_event')
    op.drop_column('event_table', 'location')
    op.drop_column('council_table', 'description')
    op.add_column('album_table', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'album_table', type_='foreignkey')
    op.drop_column('album_table', 'photographer_id')
    op.drop_column('album_table', 'desc_en')
    op.drop_column('album_table', 'desc_sv')
    op.drop_column('album_table', 'title_en')
    op.drop_column('album_table', 'title_sv')
    op.drop_column('album_table', 'date')
    op.drop_column('album_table', 'location')
    op.drop_column('album_table', 'year')
    op.drop_table('user_door_access_table')
    # ### end Alembic commands ###
