"""chore(migration): auto-generated on 9fcb429759ebb186afef58f49470a29e3f9043d2

Revision ID: c70209a62c27
Revises: f8de51ea2a13
Create Date: 2025-08-06 15:38:38.139989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c70209a62c27'
down_revision: Union[str, None] = 'f8de51ea2a13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
