"""chore(migration): auto-generated on 8aa3eafdbd00918bf036a04af8338e7a11bcea95

Revision ID: c8220db9cc8b
Revises: 355587cbf246
Create Date: 2026-01-27 15:04:18.383921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8220db9cc8b'
down_revision: Union[str, None] = '355587cbf246'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
