"""chore(migration): auto-generated on a05aaa1695721a56445e818eb0b02f8668e41d04

Revision ID: c85cf8627725
Revises: 279e097dc5f4
Create Date: 2025-07-28 13:52:23.511303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c85cf8627725'
down_revision: Union[str, None] = '279e097dc5f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('adventure_mission_table', 'description',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.String(length=2000),
               existing_nullable=False)
    op.alter_column('car_block_table', 'reason',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000),
               existing_nullable=False)
    op.alter_column('council_table', 'description_sv',
               existing_type=sa.VARCHAR(length=2500),
               type_=sa.String(length=3500),
               existing_nullable=True)
    op.alter_column('council_table', 'description_en',
               existing_type=sa.VARCHAR(length=2500),
               type_=sa.String(length=3500),
               existing_nullable=True)
    op.alter_column('election_table', 'description',
               existing_type=sa.VARCHAR(length=2000),
               type_=sa.String(length=5000),
               existing_nullable=True)
    op.alter_column('nollning_table', 'description',
               existing_type=sa.VARCHAR(length=2000),
               type_=sa.String(length=4000),
               existing_nullable=False)
    op.alter_column('post_table', 'description_sv',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.String(length=2000),
               existing_nullable=False)
    op.alter_column('post_table', 'description_en',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.String(length=2000),
               existing_nullable=False)
    op.alter_column('room_booking_table', 'description',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=1000),
               existing_nullable=True)
    op.alter_column('song_table', 'content',
               existing_type=sa.VARCHAR(length=3000),
               type_=sa.String(length=5000),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('song_table', 'content',
               existing_type=sa.String(length=5000),
               type_=sa.VARCHAR(length=3000),
               existing_nullable=False)
    op.alter_column('room_booking_table', 'description',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('post_table', 'description_en',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=300),
               existing_nullable=False)
    op.alter_column('post_table', 'description_sv',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=300),
               existing_nullable=False)
    op.alter_column('nollning_table', 'description',
               existing_type=sa.String(length=4000),
               type_=sa.VARCHAR(length=2000),
               existing_nullable=False)
    op.alter_column('election_table', 'description',
               existing_type=sa.String(length=5000),
               type_=sa.VARCHAR(length=2000),
               existing_nullable=True)
    op.alter_column('council_table', 'description_en',
               existing_type=sa.String(length=3500),
               type_=sa.VARCHAR(length=2500),
               existing_nullable=True)
    op.alter_column('council_table', 'description_sv',
               existing_type=sa.String(length=3500),
               type_=sa.VARCHAR(length=2500),
               existing_nullable=True)
    op.alter_column('car_block_table', 'reason',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
    op.alter_column('adventure_mission_table', 'description',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=False)
    # ### end Alembic commands ###
