"""chore(migration): auto-generated on b488907b66a040843b3d5b45fed7525f24c9cd1d

Revision ID: ca7dd26581a2
Revises: 08ca8f1cd7d0
Create Date: 2025-09-10 16:52:57.602452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca7dd26581a2'
down_revision: Union[str, None] = '08ca8f1cd7d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
