"""chore(migration): auto-generated on dc2d68d91204897ed634cbded0051a092f3f7112

Revision ID: cb3be75c9ef1
Revises: 10c7e649634f
Create Date: 2026-08-15 16:47:51.396944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb3be75c9ef1'
down_revision: Union[str, None] = '10c7e649634f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enclose_moose_level_table',
    sa.Column('level_id', sa.Integer(), nullable=False),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('day_index', sa.Integer(), nullable=True),
    sa.Column('name_sv', sa.String(length=100), nullable=False),
    sa.Column('name_en', sa.String(length=100), nullable=False),
    sa.Column('encoded_grid', sa.String(length=10000), nullable=False),
    sa.Column('wall_budget', sa.Integer(), nullable=False),
    sa.Column('optimal_score', sa.Integer(), nullable=False),
    sa.Column('optimal_solution', sa.JSON(), nullable=False),
    sa.Column('optimal_is_unique', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('level_id')
    )
    op.create_table('enclose_moose_submission_table',
    sa.Column('level_id', sa.Integer(), nullable=False),
    sa.Column('submission_time', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('player_score', sa.Integer(), nullable=False),
    sa.Column('player_solution', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['level_id'], ['enclose_moose_level_table.level_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['user_table.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('level_id', 'player_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('enclose_moose_submission_table')
    op.drop_table('enclose_moose_level_table')
    # ### end Alembic commands ###
