"""chore(migration): auto-generated on eeae32faa884d3ecfdb5762b35c4434ee04a3720

Revision ID: cc595fa41c78
Revises: 3e3f462da872
Create Date: 2025-07-24 14:50:55.671541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc595fa41c78'
down_revision: Union[str, None] = '3e3f462da872'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
