"""chore(migration): auto-generated on 28f29f2e79ca262b9f48716006ab6a211fe38eb8

Revision ID: cfed39828f65
Revises: de17c545e41d
Create Date: 2025-07-30 13:03:48.749722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cfed39828f65'
down_revision: Union[str, None] = 'de17c545e41d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('group_mission_table', 'is_accepted',
               existing_type=postgresql.ENUM('Accepted', 'Failed', 'Review', name='mission_status'),
               type_=sa.Enum('Accepted', 'Failed', 'Review', native_enum=False),
               existing_nullable=False)
    op.alter_column('post_door_access_table', 'door',
               existing_type=sa.VARCHAR(length=12),
               type_=sa.Enum('Ledningscentralen', 'Ambassaden', 'Syster Kents', 'Hilbert Cafe', 'Cafeförrådet', 'Sexmästeriets Förråd', 'Pubförrådet', 'Sopkomprimatorn', 'Arkivet', native_enum=False),
               existing_nullable=False)
    op.alter_column('user_door_access_table', 'door',
               existing_type=sa.VARCHAR(length=12),
               type_=sa.Enum('Ledningscentralen', 'Ambassaden', 'Syster Kents', 'Hilbert Cafe', 'Cafeförrådet', 'Sexmästeriets Förråd', 'Pubförrådet', 'Sopkomprimatorn', 'Arkivet', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_door_access_table', 'door',
               existing_type=sa.Enum('Ledningscentralen', 'Ambassaden', 'Syster Kents', 'Hilbert Cafe', 'Cafeförrådet', 'Sexmästeriets Förråd', 'Pubförrådet', 'Sopkomprimatorn', 'Arkivet', native_enum=False),
               type_=sa.VARCHAR(length=12),
               existing_nullable=False)
    op.alter_column('post_door_access_table', 'door',
               existing_type=sa.Enum('Ledningscentralen', 'Ambassaden', 'Syster Kents', 'Hilbert Cafe', 'Cafeförrådet', 'Sexmästeriets Förråd', 'Pubförrådet', 'Sopkomprimatorn', 'Arkivet', native_enum=False),
               type_=sa.VARCHAR(length=12),
               existing_nullable=False)
    op.alter_column('group_mission_table', 'is_accepted',
               existing_type=sa.Enum('Accepted', 'Failed', 'Review', native_enum=False),
               type_=postgresql.ENUM('Accepted', 'Failed', 'Review', name='mission_status'),
               existing_nullable=False)
    # ### end Alembic commands ###
