"""chore(migration): auto-generated on 3a0538e89b83ff06daebacd66366a03f7b5d7e68

Revision ID: d19ec460d5aa
Revises: 0a77ff84dca2
Create Date: 2025-07-26 23:57:23.115142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd19ec460d5aa'
down_revision: Union[str, None] = '0a77ff84dca2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
