"""chore(migration): auto-generated on b8c76944c9e646c1b998ab974a0d2e55f3b0ad81

Revision ID: d3634510f1c5
Revises: 98f778f2227f
Create Date: 2025-08-14 16:08:25.531874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3634510f1c5'
down_revision: Union[str, None] = '98f778f2227f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('album_table', 'title_sv',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.String(length=300),
               existing_nullable=False)
    op.alter_column('album_table', 'title_en',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.String(length=300),
               existing_nullable=False)
    op.alter_column('album_table', 'desc_sv',
               existing_type=sa.VARCHAR(length=123),
               type_=sa.String(length=2000),
               existing_nullable=False)
    op.alter_column('album_table', 'desc_en',
               existing_type=sa.VARCHAR(length=123),
               type_=sa.String(length=2000),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('album_table', 'desc_en',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=123),
               existing_nullable=False)
    op.alter_column('album_table', 'desc_sv',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=123),
               existing_nullable=False)
    op.alter_column('album_table', 'title_en',
               existing_type=sa.String(length=300),
               type_=sa.VARCHAR(length=40),
               existing_nullable=False)
    op.alter_column('album_table', 'title_sv',
               existing_type=sa.String(length=300),
               type_=sa.VARCHAR(length=40),
               existing_nullable=False)
    # ### end Alembic commands ###
