"""chore(migration): auto-generated on 5d9c329e11c99675bc61117f8ee142b4a8508383

Revision ID: d411faa75bbe
Revises: 08ca8f1cd7d0
Create Date: 2025-09-16 07:50:19.883836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd411faa75bbe'
down_revision: Union[str, None] = '08ca8f1cd7d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
