"""chore(migration): auto-generated on 50e20cf8efd136e6cbe83b124c4b372dd25670ee

Revision ID: d57390e0ff04
Revises: 7de0c70638e6
Create Date: 2025-07-24 11:58:25.614822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd57390e0ff04'
down_revision: Union[str, None] = '7de0c70638e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
