"""chore(migration): auto-generated on b16deea78eb475596b1efdcd2b0a8fbc90158ff5

Revision ID: d638c3b9e71f
Revises: 0bf8eeaa4844
Create Date: 2025-08-18 19:53:17.551637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd638c3b9e71f'
down_revision: Union[str, None] = '0bf8eeaa4844'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
