"""chore(migration): auto-generated on 45e63d964192b03009eb72ac30d3ff8672ca40cd

Revision ID: de17c545e41d
Revises: 58ef994bb4f9
Create Date: 2025-07-29 21:32:01.755153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de17c545e41d'
down_revision: Union[str, None] = '58ef994bb4f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('group_mission_table', 'is_accepted',
               existing_type=sa.BOOLEAN(),
               type_=sa.Enum('Accepted', 'Failed', 'Review', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('group_mission_table', 'is_accepted',
               existing_type=sa.Enum('Accepted', 'Failed', 'Review', native_enum=False),
               type_=sa.BOOLEAN(),
               existing_nullable=False)
    # ### end Alembic commands ###
