"""chore(migration): auto-generated on 93a64ba1305f051ac51e1d982c36090cfb71ab1c

Revision ID: e5a55f7c9a3e
Revises: d3634510f1c5
Create Date: 2025-08-16 13:35:09.085612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5a55f7c9a3e'
down_revision: Union[str, None] = 'd3634510f1c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
