"""chore(migration): auto-generated on 19e61dd117694124b28fdbbe0b9fefe16834ffd5

Revision ID: eb0413f8eba3
Revises: 05bcabd34057
Create Date: 2025-07-25 11:23:02.444054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb0413f8eba3'
down_revision: Union[str, None] = '05bcabd34057'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
