"""chore(migration): auto-generated on ff67194b0aee584e7a0d32e383ae1a19ceafaadb

Revision ID: ee1817f8667a
Revises: 58ef994bb4f9
Create Date: 2025-07-29 13:03:55.205266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee1817f8667a'
down_revision: Union[str, None] = '58ef994bb4f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
