"""added cols to event model

Revision ID: f0bf22d8afce
Revises: a6a861ab04ae
Create Date: 2026-07-05 17:44:47.781480

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "f0bf22d8afce"
down_revision: Union[str, None] = "a6a861ab04ae"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("event_table", sa.Column("mentor_group_types", sa.JSON(), nullable=False, server_default="[]"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("event_table", "mentor_group_types")
    # ### end Alembic commands ###
