"""chore(migration): auto-generated on f5a24acf794c1b2586e9808aef89a29b9de688d2

Revision ID: f79277238b13
Revises: 3e3f462da872
Create Date: 2025-07-24 19:07:48.005230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f79277238b13'
down_revision: Union[str, None] = '3e3f462da872'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
