"""chore(migration): auto-generated on 0f1346a5e91e7f86b2346200e9d7e80e9e9e6dfa

Revision ID: f8de51ea2a13
Revises: 608a17ac0dfc
Create Date: 2025-08-06 14:46:42.738773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8de51ea2a13'
down_revision: Union[str, None] = '608a17ac0dfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event_user_table', 'drinkPackage',
               existing_type=sa.VARCHAR(length=14),
               type_=sa.Enum('None', 'AlcoholFree', 'Alcohol', native_enum=False),
               existing_nullable=False)
    op.add_column('nollning_group_table', sa.Column('mentor_group_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nollning_group_table', 'mentor_group_number')
    op.alter_column('event_user_table', 'drinkPackage',
               existing_type=sa.Enum('None', 'AlcoholFree', 'Alcohol', native_enum=False),
               type_=sa.VARCHAR(length=14),
               existing_nullable=False)
    # ### end Alembic commands ###
