"""chore(migration): auto-generated on b21b28b48b3f52f8cd3bcda7738189c7e71e1b42

Revision ID: fa68f5bd63fa
Revises: 0bf8eeaa4844
Create Date: 2025-08-18 19:07:42.133591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa68f5bd63fa'
down_revision: Union[str, None] = '0bf8eeaa4844'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
