"""chore(migration): auto-generated on 0f26f897fc610bfc1781bf511ab971b6c0b950b5

Revision ID: fc9e9a8345d9
Revises: d3634510f1c5
Create Date: 2025-08-16 17:21:05.706342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc9e9a8345d9'
down_revision: Union[str, None] = 'd3634510f1c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
